apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{PVC_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app.kubernetes.io/name: sandbox
    app.kubernetes.io/component: workspace
    endian.io/project-id: "{{PROJECT_ID}}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{STORAGE_CLASS}}
  resources:
    requests:
      storage: {{PVC_SIZE}}
