#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${ROOT_DIR}/infra/terraform"
OVERLAY_DIR="${ROOT_DIR}/infra/k8s/overlays/prod"
GENERATED="${OVERLAY_DIR}/generated/terraform-config.yaml"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform is required" >&2
  exit 1
fi

if ! terraform -chdir="${TF_DIR}" output -json >/dev/null 2>&1; then
  echo "terraform outputs unavailable — run 'terraform apply' first" >&2
  exit 1
fi

TF_JSON="$(terraform -chdir="${TF_DIR}" output -json)"

get_output() {
  local key="$1"
  echo "${TF_JSON}" | python3 -c "import json,sys; print(json.load(sys.stdin)['${key}']['value'])"
}

ARTIFACT_REGISTRY_URL="$(get_output artifact_registry_url)"
GKE_CLUSTER_NAME="$(get_output gke_cluster_name)"
GKE_LOCATION="$(get_output gke_location)"
CLOUD_SQL_CONNECTION="$(get_output cloud_sql_connection_name)"
PREVIEW_DOMAIN="$(get_output preview_domain)"
PLATFORM_DOMAIN="$(get_output platform_domain)"
PLATFORM_SA_EMAIL="$(get_output platform_service_account_email)"
SANDBOX_SA_EMAIL="$(get_output sandbox_service_account_email)"
PROJECT_ID="$(get_output project_id)"

ACME_EMAIL="${ACME_EMAIL:-admin@${PLATFORM_DOMAIN#platform.}}"

replace_in_file() {
  local file="$1"
  sed -i.bak \
    -e "s|PLACEHOLDER_ARTIFACT_REGISTRY|${ARTIFACT_REGISTRY_URL}|g" \
    -e "s|PLACEHOLDER_GKE_CLUSTER_NAME|${GKE_CLUSTER_NAME}|g" \
    -e "s|PLACEHOLDER_GKE_LOCATION|${GKE_LOCATION}|g" \
    -e "s|PLACEHOLDER_CLOUD_SQL_CONNECTION|${CLOUD_SQL_CONNECTION}|g" \
    -e "s|PLACEHOLDER_PREVIEW_DOMAIN|${PREVIEW_DOMAIN}|g" \
    -e "s|PLACEHOLDER_PLATFORM_HOST|${PLATFORM_DOMAIN}|g" \
    -e "s|PLACEHOLDER_PLATFORM_SA_EMAIL|${PLATFORM_SA_EMAIL}|g" \
    -e "s|PLACEHOLDER_SANDBOX_SA_EMAIL|${SANDBOX_SA_EMAIL}|g" \
    -e "s|PLACEHOLDER_GCP_PROJECT_ID|${PROJECT_ID}|g" \
    -e "s|PLACEHOLDER_ACME_EMAIL|${ACME_EMAIL}|g" \
    "${file}"
  rm -f "${file}.bak"
}

echo "Rendering ${GENERATED}"
cat > "${GENERATED}" <<EOF
# Generated by scripts/render-kustomize-prod.sh — do not edit by hand.
apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-config
  namespace: endian-platform
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/component: config
data:
  gke_cluster_name: ${GKE_CLUSTER_NAME}
  gke_location: ${GKE_LOCATION}
  artifact_registry_url: ${ARTIFACT_REGISTRY_URL}
  cloud_sql_connection_name: ${CLOUD_SQL_CONNECTION}
  preview_domain: ${PREVIEW_DOMAIN}
  platform_domain: ${PLATFORM_DOMAIN}
  platform_service_account_email: ${PLATFORM_SA_EMAIL}
EOF

PROD_FILES=(
  "${OVERLAY_DIR}/kustomization.yaml"
  "${OVERLAY_DIR}/platform-deployment-patch.yaml"
  "${OVERLAY_DIR}/platform-ingress-patch.yaml"
  "${OVERLAY_DIR}/platform-secrets.yaml"
  "${OVERLAY_DIR}/platform-serviceaccount-patch.yaml"
  "${OVERLAY_DIR}/sandbox-serviceaccount-patch.yaml"
  "${OVERLAY_DIR}/cert-manager-clusterissuer.yaml"
)

for f in "${PROD_FILES[@]}"; do
  replace_in_file "${f}"
done

echo "Prod overlay rendered:"
echo "  artifact_registry_url=${ARTIFACT_REGISTRY_URL}"
echo "  preview_domain=${PREVIEW_DOMAIN}"
echo "  platform_domain=${PLATFORM_DOMAIN}"
