apiVersion: v1
kind: Service
metadata:
  name: platform
  namespace: endian-platform
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform
  ports:
    - name: http
      port: 80
      targetPort: http
