apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-provisioner
  namespace: endian-platform
  annotations:
    iam.gke.io/gcp-service-account: platform-runtime-prod@project-5be3cb47-0a28-4053-b3a.iam.gserviceaccount.com
