apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-runtime
  namespace: endian-sandboxes
  annotations:
    iam.gke.io/gcp-service-account: sandbox-runtime-prod@project-5be3cb47-0a28-4053-b3a.iam.gserviceaccount.com
